import './globals.css';
import { AuthProvider } from '../context/authContext'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js'
}

export default function RootLayout({children}){
    return(
        <AuthProvider>
            <html lang="en">
                <body className='w-full'>
                    {children}
                </body>
            </html>    
        </AuthProvider>
    )
}